# Actividad M2.1 Uso de Google Colab

Ana Daniela López Dávila | A00831568

In [ ]:
#Importar la librería pandas.
import pandas as pd

## Aportación de compañero
Conforme a los observado, me agradó la estructura que le diste a tu trabajo. Considero que una buena práctica al momento de programar es siempre agregar comentarios a lo largo del código, ya que si una tercera persona necesita agregar o modificar, tiene primero que saber el contexto y lo que hace el código. Concuerdo con el procedimiento que seguiste y la solución que diste a cada pregunta.

-Paola Guadalupe Machorro Ortiz :)

## Aportación mia en el documento de un compañero

![Captura de Pantalla 2022-04-09 a la(s) 8.05.49 p.m..png]()

## Lectura de datos

In [ ]:
#Guarda en un dataframe el contenido del dataset proporcionado.
data = pd.read_csv('/content/drive/MyDrive/Actividad Formativa M2.1/titanic.csv')

In [ ]:
#Verifica que el archivo cargado en Google Colab corresponde con el archivo csv, mostrando  
#los primeros y los últimos renglones del "data frame"
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Descripción de Variables

In [ ]:
#Identifica el tipo de variables presentes en el dataset
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


**¿Cuáles variables son categóricas y cuáles numéricas?**

1.   PassengerId es    *numérica*
2.   Survived es   *numérica*
3.   Pclass es  *numérica*
4.   Name es *categórica*
5.   Sex es  *categórica*
6.   Age es *numérica*
7.   SibSp es *numérica*
8.   Parch es *numérica*
9.   Ticket es *categórica*
10.  Fare es *numérica*
11.  Cabin es *categórica*
12.  Embarked es *categórica*

El método .columns, regresa el nombre de cada una de las columnas en el dataframe

In [ ]:
#columns
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

El método .info(), al inicio regresa el número de registros, su index inicial y final, y el número total de columnas. Luego regresa el número de columna, su nombre, cuantos valores no nulos tiene en total, y el tipo de dato de cada columna. Al final, también regresa el número de columnas por cada tipo de dato y la memoria que se usa.

In [ ]:
#info()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**¿Cuántos registros se tienen en total?**

En total se tienen 891 registros

**¿Cuáles tienen valores nulos?** 

Las columnas 'Age', 'Cabin' y 'Embarked contienen valores nulos

**¿Cuáles no tienen valores nulos?**

Las columnas 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'SibSp', 'Parch', 'Ticket' y 'Fare' no contienen valores nulos

El método .describe() da un análisis descriptivo del dataframe. Contiene el número total de datos, el promedio, la variación estándar, el valor mínimo y máximo, y los cuartiles de cada columna que contenga variables numéricas

In [ ]:
#describe()
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**¿Qué columnas aparecen en el resultado de describe?**

En el resultado de describe, solo aparecen aquellas columnas que contenan datos numéricos para poder hacer las operaciones ya antes mencionadas. En este caso serían las columnas: 'PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch' y 'Fare'
 
**¿Cuál es la tarifa más cara?**

La tarifa más cara equivale a 512 (512.3292)

**¿Cuál es el promedio de edad?**

El promedio de la edad es de 30 (29.699118)

**¿Cuántos valores diferentes se tiene por categoría?**



*   PassengerId tiene 891 valores diferentes
*   Sex tiene 2 valores diferentes
*   Ticket tiene 681 valores diferentes
*   Cabin tiene 148 valores diferentes
*   Embarked tiene 4 valores diferentes

A continuación se muestra el despliegue de esos valores diferentes usando el método .unique() por cada columna

In [ ]:
#Columna 'Name'
name = data['Name'].unique()
print('Cantidad de valores diferentes en la columna "Name": ', len(name))
print()
name

Cantidad de valores diferentes en la columna "Name":  891

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
       'Emir, Mr. Farred Chehab', 'Fortune, Mr. Charles Alexander',
       'O\'Dwyer, Miss. Ellen "Nellie"', 'Todoroff, Mr. Lalio',
       'Uruchurtu, Don. Manuel E',
       'Spencer, Mrs. William Augustus (Marie Eugenie)',
       'Glynn, Miss. Mary Agatha', 'Wheadon, Mr. Edward H',
       'Meyer, Mr. Edgar Joseph', 'Holverson, Mr. Alexander Oskar',
       'Mamee, Mr. Hanna', 'Cann, Mr. Ernest Charles',
       'Vander Planke, Miss. Augusta Maria',
       'Nicola-Yarred, Miss. Jamila',
       'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
       'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
       'Kraeff, Mr. Theodor', 'Laroche, Miss. Simonne Marie Anne Andree',
       'Devaney, Miss. Margaret Delia', 'Rogers, Mr. William John',
       'Lennon, Mr. Denis', "O'Driscoll, Miss. Bridget",
       'Samaan, Mr. Youssef',
       'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
       'Panula, Master. Juha Niilo', 'Nosworthy, Mr. Richard Cater',
       'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
       'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
       'Ostby, Mr. Engelhart Cornelius', 'Woolner, Mr. Hugh',
       'Rugg, Miss. Emily', 'Novel, Mr. Mansouer',
       'West, Miss. Constance Mirium',
       'Goodwin, Master. William Frederick', 'Sirayanian, Mr. Orsen',
       'Icard, Miss. Amelie', 'Harris, Mr. Henry Birkhardt',
       'Skoog, Master. Harald', 'Stewart, Mr. Albert A',
       'Moubarek, Master. Gerios', 'Nye, Mrs. (Elizabeth Ramell)',
       'Crease, Mr. Ernest James', 'Andersson, Miss. Erna Alexandra',
       'Kink, Mr. Vincenz', 'Jenkin, Mr. Stephen Curnow',
       'Goodwin, Miss. Lillian Amy', 'Hood, Mr. Ambrose Jr',
       'Chronopoulos, Mr. Apostolos', 'Bing, Mr. Lee',
       'Moen, Mr. Sigurd Hansen', 'Staneff, Mr. Ivan',
       'Moutal, Mr. Rahamin Haim', 'Caldwell, Master. Alden Gates',
       'Dowdell, Miss. Elizabeth', 'Waelens, Mr. Achille',
       'Sheerlinck, Mr. Jan Baptist', 'McDermott, Miss. Brigdet Delia',
       'Carrau, Mr. Francisco M', 'Ilett, Miss. Bertha',
       'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
       'Ford, Mr. William Neal', 'Slocovski, Mr. Selman Francis',
       'Fortune, Miss. Mabel Helen', 'Celotti, Mr. Francesco',
       'Christmann, Mr. Emil', 'Andreasson, Mr. Paul Edvin',
       'Chaffee, Mr. Herbert Fuller', 'Dean, Mr. Bertram Frank',
       'Coxon, Mr. Daniel', 'Shorney, Mr. Charles Joseph',
       'Goldschmidt, Mr. George B', 'Greenfield, Mr. William Bertram',
       'Doling, Mrs. John T (Ada Julia Bone)', 'Kantor, Mr. Sinai',
       'Petranec, Miss. Matilda', 'Petroff, Mr. Pastcho ("Pentcho")',
       'White, Mr. Richard Frasar', 'Johansson, Mr. Gustaf Joel',
       'Gustafsson, Mr. Anders Vilhelm', 'Mionoff, Mr. Stoytcho',
       'Salkjelsvik, Miss. Anna Kristine', 'Moss, Mr. Albert Johan',
       'Rekic, Mr. Tido', 'Moran, Miss. Bertha',
       'Porter, Mr. Walter Chamberlain', 'Zabour, Miss. Hileni',
       'Barton, Mr. David John', 'Jussila, Miss. Katriina',
       'Attalah, Miss. Malake', 'Pekoniemi, Mr. Edvard',
       'Connors, Mr. Patrick', 'Turpin, Mr. William John Robert',
       'Baxter, Mr. Quigg Edmond', 'Andersson, Miss. Ellis Anna Maria',
       'Hickman, Mr. Stanley George', 'Moore, Mr. Leonard Charles',
       'Nasser, Mr. Nicholas', 'Webber, Miss. Susan',
       'White, Mr. Percival Wayland', 'Nicola-Yarred, Master. Elias',
       'McMahon, Mr. Martin', 'Madsen, Mr. Fridtjof Arne',
       'Peter, Miss. Anna', 'Ekstrom, Mr. Johan', 'Drazenoic, Mr. Jozef',
       'Coelho, Mr. Domingos Fernandeo',
       'Robins, Mrs. Alexander A (Grace Charity Laury)',
       'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
       'Sobey, Mr. Samuel James Hayden', 'Richard, Mr. Emile',
       'Newsom, Miss. Helen Monypeny', 'Futrelle, Mr. Jacques Heath',
       'Osen, Mr. Olaf Elon', 'Giglio, Mr. Victor',
       'Boulos, Mrs. Joseph (Sultana)', 'Nysten, Miss. Anna Sofia',
       'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
       'Burke, Mr. Jeremiah', 'Andrew, Mr. Edgardo Samuel',
       'Nicholls, Mr. Joseph Charles',
       'Andersson, Mr. August Edvard ("Wennerstrom")',
       'Ford, Miss. Robina Maggie "Ruby"',
       'Navratil, Mr. Michel ("Louis M Hoffman")',
       'Byles, Rev. Thomas Roussel Davids', 'Bateman, Rev. Robert James',
       'Pears, Mrs. Thomas (Edith Wearne)', 'Meo, Mr. Alfonzo',
       'van Billiard, Mr. Austin Blyler', 'Olsen, Mr. Ole Martin',
       'Williams, Mr. Charles Duane', 'Gilnagh, Miss. Katherine "Katie"',
       'Corn, Mr. Harry', 'Smiljanic, Mr. Mile',
       'Sage, Master. Thomas Henry', 'Cribb, Mr. John Hatfield',
       'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
       'Bengtsson, Mr. John Viktor', 'Calic, Mr. Jovo',
       'Panula, Master. Eino Viljami',
       'Goldsmith, Master. Frank John William "Frankie"',
       'Chibnall, Mrs. (Edith Martha Bowerman)',
       'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
       'Baumann, Mr. John D', 'Ling, Mr. Lee',
       'Van der hoef, Mr. Wyckoff', 'Rice, Master. Arthur',
       'Johnson, Miss. Eleanor Ileen', 'Sivola, Mr. Antti Wilhelm',
       'Smith, Mr. James Clinch', 'Klasen, Mr. Klas Albin',
       'Lefebre, Master. Henry Forbes', 'Isham, Miss. Ann Elizabeth',
       'Hale, Mr. Reginald', 'Leonard, Mr. Lionel',
       'Sage, Miss. Constance Gladys', 'Pernot, Mr. Rene',
       'Asplund, Master. Clarence Gustaf Hugo',
       'Becker, Master. Richard F', 'Kink-Heilmann, Miss. Luise Gretchen',
       'Rood, Mr. Hugh Roscoe',
       'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
       'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
       'Bourke, Mr. John', 'Turcin, Mr. Stjepan', 'Pinsky, Mrs. (Rosa)',
       'Carbines, Mr. William',
       'Andersen-Jensen, Miss. Carla Christine Nielsine',
       'Navratil, Master. Michel M',
       'Brown, Mrs. James Joseph (Margaret Tobin)',
       'Lurette, Miss. Elise', 'Mernagh, Mr. Robert',
       'Olsen, Mr. Karl Siegwart Andreas',
       'Madigan, Miss. Margaret "Maggie"',
       'Yrois, Miss. Henriette ("Mrs Harbeck")',
       'Vande Walle, Mr. Nestor Cyriel', 'Sage, Mr. Frederick',
       'Johanson, Mr. Jakob Alfred', 'Youseff, Mr. Gerious',
       'Cohen, Mr. Gurshon "Gus"', 'Strom, Miss. Telma Matilda',
       'Backstrom, Mr. Karl Alfred', 'Albimona, Mr. Nassef Cassem',
       'Carr, Miss. Helen "Ellen"', 'Blank, Mr. Henry', 'Ali, Mr. Ahmed',
       'Cameron, Miss. Clear Annie', 'Perkin, Mr. John Henry',
       'Givard, Mr. Hans Kristensen', 'Kiernan, Mr. Philip',
       'Newell, Miss. Madeleine', 'Honkanen, Miss. Eliina',
       'Jacobsohn, Mr. Sidney Samuel', 'Bazzani, Miss. Albina',
       'Harris, Mr. Walter', 'Sunderland, Mr. Victor Francis',
       'Bracken, Mr. James H', 'Green, Mr. George Henry',
       'Nenkoff, Mr. Christo', 'Hoyt, Mr. Frederick Maxfield',
       'Berglund, Mr. Karl Ivar Sven', 'Mellors, Mr. William John',
       'Lovell, Mr. John Hall ("Henry")', 'Fahlstrom, Mr. Arne Jonas',
       'Lefebre, Miss. Mathilde',
       'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
       'Larsson, Mr. Bengt Edvin', 'Sjostedt, Mr. Ernst Adolf',
       'Asplund, Miss. Lillian Gertrud',
       'Leyson, Mr. Robert William Norman',
       'Harknett, Miss. Alice Phoebe', 'Hold, Mr. Stephen',
       'Collyer, Miss. Marjorie "Lottie"',
       'Pengelly, Mr. Frederick William', 'Hunt, Mr. George Henry',
       'Zabour, Miss. Thamine', 'Murphy, Miss. Katherine "Kate"',
       'Coleridge, Mr. Reginald Charles', 'Maenpaa, Mr. Matti Alexanteri',
       'Attalah, Mr. Sleiman', 'Minahan, Dr. William Edward',
       'Lindahl, Miss. Agda Thorilda Viktoria',
       'Hamalainen, Mrs. William (Anna)', 'Beckwith, Mr. Richard Leonard',
       'Carter, Rev. Ernest Courtenay', 'Reed, Mr. James George',
       'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
       'Stead, Mr. William Thomas', 'Lobb, Mr. William Arthur',
       'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
       'Touma, Mrs. Darwis (Hanne Youssef Razi)',
       'Thorne, Mrs. Gertrude Maybelle', 'Cherry, Miss. Gladys',
       'Ward, Miss. Anna', 'Parrish, Mrs. (Lutie Davis)',
       'Smith, Mr. Thomas', 'Asplund, Master. Edvin Rojj Felix',
       'Taussig, Mr. Emil', 'Harrison, Mr. William', 'Henry, Miss. Delia',
       'Reeves, Mr. David', 'Panula, Mr. Ernesti Arvid',
       'Persson, Mr. Ernst Ulrik',
       'Graham, Mrs. William Thompson (Edith Junkins)',
       'Bissette, Miss. Amelia', 'Cairns, Mr. Alexander',
       'Tornquist, Mr. William Henry',
       'Mellinger, Mrs. (Elizabeth Anne Maidment)',
       'Natsch, Mr. Charles H', 'Healy, Miss. Hanora "Nora"',
       'Andrews, Miss. Kornelia Theodosia',
       'Lindblom, Miss. Augusta Charlotta', 'Parkes, Mr. Francis "Frank"',
       'Rice, Master. Eric', 'Abbott, Mrs. Stanton (Rosa Hunt)',
       'Duane, Mr. Frank', 'Olsson, Mr. Nils Johan Goransson',
       'de Pelsmaeker, Mr. Alfons', 'Dorking, Mr. Edward Arthur',
       'Smith, Mr. Richard William', 'Stankovic, Mr. Ivan',
       'de Mulder, Mr. Theodore', 'Naidenoff, Mr. Penko',
       'Hosono, Mr. Masabumi', 'Connolly, Miss. Kate',
       'Barber, Miss. Ellen "Nellie"',
       'Bishop, Mrs. Dickinson H (Helen Walton)',
       'Levy, Mr. Rene Jacques', 'Haas, Miss. Aloisia',
       'Mineff, Mr. Ivan', 'Lewy, Mr. Ervin G', 'Hanna, Mr. Mansour',
       'Allison, Miss. Helen Loraine', 'Saalfeld, Mr. Adolphe',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Kelly, Miss. Anna Katherine "Annie Kate"', 'McCoy, Mr. Bernard',
       'Johnson, Mr. William Cahoone Jr', 'Keane, Miss. Nora A',
       'Williams, Mr. Howard Hugh "Harry"',
       'Allison, Master. Hudson Trevor', 'Fleming, Miss. Margaret',
       'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       'Abelson, Mr. Samuel', 'Francatelli, Miss. Laura Mabel',
       'Hays, Miss. Margaret Bechstein', 'Ryerson, Miss. Emily Borie',
       'Lahtinen, Mrs. William (Anna Sylfven)', 'Hendekovic, Mr. Ignjac',
       'Hart, Mr. Benjamin', 'Nilsson, Miss. Helmina Josefina',
       'Kantor, Mrs. Sinai (Miriam Sternin)', 'Moraweck, Dr. Ernest',
       'Wick, Miss. Mary Natalie',
       'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
       'Dennis, Mr. Samuel', 'Danoff, Mr. Yoto',
       'Slayter, Miss. Hilda Mary',
       'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
       'Sage, Mr. George John Jr', 'Young, Miss. Marie Grice',
       'Nysveen, Mr. Johan Hansen', 'Ball, Mrs. (Ada E Hall)',
       'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
       'Hippach, Miss. Jean Gertrude', 'McCoy, Miss. Agnes',
       'Partner, Mr. Austen', 'Graham, Mr. George Edward',
       'Vander Planke, Mr. Leo Edmondus',
       'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
       'Denkoff, Mr. Mitto', 'Pears, Mr. Thomas Clinton',
       'Burns, Miss. Elizabeth Margaret', 'Dahl, Mr. Karl Edwart',
       'Blackwell, Mr. Stephen Weart', 'Navratil, Master. Edmond Roger',
       'Fortune, Miss. Alice Elizabeth', 'Collander, Mr. Erik Gustaf',
       'Sedgwick, Mr. Charles Frederick Waddington',
       'Fox, Mr. Stanley Hubert', 'Brown, Miss. Amelia "Mildred"',
       'Smith, Miss. Marion Elsie',
       'Davison, Mrs. Thomas Henry (Mary E Finck)',
       'Coutts, Master. William Loch "William"', 'Dimic, Mr. Jovan',
       'Odahl, Mr. Nils Martin', 'Williams-Lambert, Mr. Fletcher Fellows',
       'Elias, Mr. Tannous', 'Arnold-Franchi, Mr. Josef',
       'Yousif, Mr. Wazli', 'Vanden Steen, Mr. Leo Peter',
       'Bowerman, Miss. Elsie Edith', 'Funk, Miss. Annie Clemmer',
       'McGovern, Miss. Mary', 'Mockler, Miss. Helen Mary "Ellie"',
       'Skoog, Mr. Wilhelm', 'del Carlo, Mr. Sebastiano',
       'Barbara, Mrs. (Catherine David)', 'Asim, Mr. Adola',
       "O'Brien, Mr. Thomas", 'Adahl, Mr. Mauritz Nils Martin',
       'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
       'Moussa, Mrs. (Mantoura Boulos)', 'Jermyn, Miss. Annie',
       'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles',
       'Wiklund, Mr. Jakob Alfred', 'Beavan, Mr. William Thomas',
       'Ringhini, Mr. Sante', 'Palsson, Miss. Stina Viola',
       'Meyer, Mrs. Edgar Joseph (Leila Saks)',
       'Landergren, Miss. Aurora Adelia', 'Widener, Mr. Harry Elkins',
       'Betros, Mr. Tannous', 'Gustafsson, Mr. Karl Gideon',
       'Bidois, Miss. Rosalie', 'Nakid, Miss. Maria ("Mary")',
       'Tikkanen, Mr. Juho',
       'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
       'Plotcharsky, Mr. Vasil', 'Davies, Mr. Charles Henry',
       'Goodwin, Master. Sidney Leonard', 'Buss, Miss. Kate',
       'Sadlier, Mr. Matthew', 'Lehmann, Miss. Bertha',
       'Carter, Mr. William Ernest', 'Jansson, Mr. Carl Olof',
       'Gustafsson, Mr. Johan Birger', 'Newell, Miss. Marjorie',
       'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
       'Johansson, Mr. Erik', 'Olsson, Miss. Elina',
       'McKane, Mr. Peter David', 'Pain, Dr. Alfred',
       'Trout, Mrs. William H (Jessie L)', 'Niskanen, Mr. Juha',
       'Adams, Mr. John', 'Jussila, Miss. Mari Aina',
       'Hakkarainen, Mr. Pekka Pietari', 'Oreskovic, Miss. Marija',
       'Gale, Mr. Shadrach', 'Widegren, Mr. Carl/Charles Peter',
       'Richards, Master. William Rowe',
       'Birkeland, Mr. Hans Martin Monsen', 'Lefebre, Miss. Ida',
       'Sdycoff, Mr. Todor', 'Hart, Mr. Henry', 'Minahan, Miss. Daisy E',
       'Cunningham, Mr. Alfred Fleming', 'Sundman, Mr. Johan Julian',
       'Meek, Mrs. Thomas (Annie Louise Rowley)',
       'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
       'Silven, Miss. Lyyli Karoliina', 'Matthews, Mr. William John',
       'Van Impe, Miss. Catharina', 'Gheorgheff, Mr. Stanio',
       'Charters, Mr. David', 'Zimmerman, Mr. Leo',
       'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
       'Rosblom, Mr. Viktor Richard', 'Wiseman, Mr. Phillippe',
       'Clarke, Mrs. Charles V (Ada Maria Winfield)',
       'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
       'Flynn, Mr. James', 'Pickard, Mr. Berk (Berk Trembisky)',
       'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
       'Thorneycroft, Mrs. Percival (Florence Kate White)',
       'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
       'Kallio, Mr. Nikolai Erland', 'Silvey, Mr. William Baird',
       'Carter, Miss. Lucile Polk',
       'Ford, Miss. Doolina Margaret "Daisy"',
       'Richards, Mrs. Sidney (Emily Hocking)', 'Fortune, Mr. Mark',
       'Kvillner, Mr. Johan Henrik Johannesson',
       'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 'Hampe, Mr. Leon',
       'Petterson, Mr. Johan Emil', 'Reynaldo, Ms. Encarnacion',
       'Johannesen-Bratthammer, Mr. Bernt', 'Dodge, Master. Washington',
       'Mellinger, Miss. Madeleine Violet', 'Seward, Mr. Frederic Kimber',
       'Baclini, Miss. Marie Catherine', 'Peuchen, Major. Arthur Godfrey',
       'West, Mr. Edwy Arthur', 'Hagland, Mr. Ingvald Olai Olsen',
       'Foreman, Mr. Benjamin Laventall', 'Goldenberg, Mr. Samuel L',
       'Peduzzi, Mr. Joseph', 'Jalsevac, Mr. Ivan',
       'Millet, Mr. Francis Davis', 'Kenyon, Mrs. Frederick R (Marion)',
       'Toomey, Miss. Ellen', "O'Connor, Mr. Maurice",
       'Anderson, Mr. Harry', 'Morley, Mr. William', 'Gee, Mr. Arthur H',
       'Milling, Mr. Jacob Christian', 'Maisner, Mr. Simon',
       'Goncalves, Mr. Manuel Estanslas', 'Campbell, Mr. William',
       'Smart, Mr. John Montgomery', 'Scanlan, Mr. James',
       'Baclini, Miss. Helene Barbara', 'Keefe, Mr. Arthur',
       'Cacic, Mr. Luka', 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
       'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
       'Strandberg, Miss. Ida Sofia', 'Clifford, Mr. George Quincy',
       'Renouf, Mr. Peter Henry', 'Braund, Mr. Lewis Richard',
       'Karlsson, Mr. Nils August', 'Hirvonen, Miss. Hildur E',
       'Goodwin, Master. Harold Victor',
       'Frost, Mr. Anthony Wood "Archie"', 'Rouse, Mr. Richard Henry',
       'Turkula, Mrs. (Hedwig)', 'Bishop, Mr. Dickinson H',
       'Lefebre, Miss. Jeannie',
       'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
       'Kent, Mr. Edward Austin', 'Somerton, Mr. Francis William',
       'Coutts, Master. Eden Leslie "Neville"',
       'Hagland, Mr. Konrad Mathias Reiersen', 'Windelov, Mr. Einar',
       'Molson, Mr. Harry Markland', 'Artagaveytia, Mr. Ramon',
       'Stanley, Mr. Edward Roland', 'Yousseff, Mr. Gerious',
       'Eustis, Miss. Elizabeth Mussey',
       'Shellard, Mr. Frederick William',
       'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
       'Svensson, Mr. Olof', 'Calic, Mr. Petar', 'Canavan, Miss. Mary',
       "O'Sullivan, Miss. Bridget Mary", 'Laitinen, Miss. Kristina Sofia',
       'Maioni, Miss. Roberta',
       'Penasco y Castellana, Mr. Victor de Satode',
       'Quick, Mrs. Frederick Charles (Jane Richards)',
       'Bradley, Mr. George ("George Arthur Brayton")',
       'Olsen, Mr. Henry Margido', 'Lang, Mr. Fang',
       'Daly, Mr. Eugene Patrick', 'Webber, Mr. James',
       'McGough, Mr. James Robert',
       'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
       'Coleff, Mr. Satio', 'Walker, Mr. William Anderson',
       'Lemore, Mrs. (Amelia Milley)', 'Ryan, Mr. Patrick',
       'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
       'Pavlovic, Mr. Stefo', 'Perreault, Miss. Anne', 'Vovk, Mr. Janko',
       'Lahoud, Mr. Sarkis',
       'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
       'Kassem, Mr. Fared', 'Farrell, Mr. James', 'Ridsdale, Miss. Lucy',
       'Farthing, Mr. John', 'Salonen, Mr. Johan Werner',
       'Hocking, Mr. Richard George', 'Quick, Miss. Phyllis May',
       'Toufik, Mr. Nakli', 'Elias, Mr. Joseph Jr',
       'Peter, Mrs. Catherine (Catherine Rizk)', 'Cacic, Miss. Marija',
       'Hart, Miss. Eva Miriam', 'Butt, Major. Archibald Willingham',
       'LeRoy, Miss. Bertha', 'Risien, Mr. Samuel Beard',
       'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R',
       'Andersson, Miss. Ingeborg Constanzia',
       'Andersson, Miss. Sigrid Elisabeth', 'Beane, Mr. Edward',
       'Douglas, Mr. Walter Donald', 'Nicholson, Mr. Arthur Ernest',
       'Beane, Mrs. Edward (Ethel Clarke)', 'Padro y Manent, Mr. Julian',
       'Goldsmith, Mr. Frank John', 'Davies, Master. John Morgan Jr',
       'Thayer, Mr. John Borland Jr', 'Sharp, Mr. Percival James R',
       "O'Brien, Mr. Timothy", 'Leeni, Mr. Fahim ("Philip Zenni")',
       'Ohman, Miss. Velin', 'Wright, Mr. George',
       'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
       'Robbins, Mr. Victor', 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
       'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
       'Morrow, Mr. Thomas Rowan', 'Sivic, Mr. Husein',
       'Norman, Mr. Robert Douglas', 'Simmons, Mr. John',
       'Meanwell, Miss. (Marion Ogden)', 'Davies, Mr. Alfred J',
       'Stoytcheff, Mr. Ilia',

In [ ]:
#Columna 'Sex'
sex = data['Sex'].unique()
print('Cantidad de valores diferentes en la columna "Sex": ', len(sex))
print()
sex

Cantidad de valores diferentes en la columna "Sex":  2

array(['male', 'female'], dtype=object)

In [ ]:
#Columna 'Ticket'
ticket = data['Ticket'].unique()
print('Cantidad de valores diferentes en la columna "Ticket": ', len(ticket))
print()
ticket

Cantidad de valores diferentes en la columna "Ticket":  681

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '3101278', 'W./C. 6608', 'SOTON/OQ 392086', '343275',
       '343276', '347466', 'W.E.P. 5734', 'C.A. 2315', '364500', '374910',
       'PC 17754', 'PC 17759', '231919', '244367', '349245', '349215',
       '35281', '7540', '3101276', '349207', '343120', '312991', '349249',
       '371110', '110465', '2665', '324669', '4136', '2627',
       'STON/O 2. 3101294', '370369', 'PC 17558', 'A4. 54510', '27267',
       '370372', 'C 17369', '2668', '347061', '349241',
       'SOTON/O.Q. 3101307', 'A/5. 3337', '228414', 'C.A. 29178',
       'SC/PARIS 2133', '11752', '7534', 'PC 17593', '2678', '347081',
       'STON/O2. 3101279', '365222', '231945', 'C.A. 33112', '350043',
       '230080', '244310', 'S.O.P. 1166', '113776', 'A.5. 11206',
       'A/5. 851', 'Fa 265302', 'PC 17597', '35851', 'SOTON/OQ 392090',
       '315037', 'CA. 2343', '371362', 'C.A. 33595', '347068', '315093',
       '363291', '113505', 'PC 17318', '111240', 'STON/O 2. 3101280',
       '17764', '350404', '4133', 'PC 17595', '250653', 'LINE',
       'SC/PARIS 2131', '230136', '315153', '113767', '370365', '111428',
       '364849', '349247', '234604', '28424', '350046', 'PC 17610',
       '368703', '4579', '370370', '248747', '345770', '3101264', '2628',
       'A/5 3540', '347054', '2699', '367231', '112277',
       'SOTON/O.Q. 3101311', 'F.C.C. 13528', 'A/5 21174', '250646',
       '367229', '35273', 'STON/O2. 3101283', '243847', '11813',
       'W/C 14208', 'SOTON/OQ 392089', '220367', '21440', '349234',
       '19943', 'PP 4348', 'SW/PP 751', 'A/5 21173', '236171', '347067',
       '237442', 'C.A. 29566', 'W./C. 6609', '26707', 'C.A. 31921',
       '28665', 'SCO/W 1585', '367230', 'W./C. 14263',
       'STON/O 2. 3101275', '2694', '19928', '347071', '250649', '11751',
       '244252', '362316', '113514', 'A/5. 3336', '370129', '2650',
       'PC 17585', '110152', 'PC 17755', '230433', '384461', '110413',
       '112059', '382649', 'C.A. 17248', '347083', 'PC 17582', 'PC 17760',
       '113798', '250644', 'PC 17596', '370375', '13502', '347073',
       '239853', 'C.A. 2673', '336439', '347464', '345778', 'A/5. 10482',
       '113056', '349239', '345774', '349206', '237798', '370373',
       '19877', '11967', 'SC/Paris 2163', '349236', '349233', 'PC 17612',
       '2693', '113781', '19988', '9234', '367226', '226593', 'A/5 2466',
       '17421', 'PC 17758', 'P/PP 3381', 'PC 17485', '11767', 'PC 17608',
       '250651', '349243', 'F.C.C. 13529', '347470', '29011', '36928',
       '16966', 'A/5 21172', '349219', '234818', '345364', '28551',
       '111361', '113043', 'PC 17611', '349225', '7598', '113784',
       '248740', '244361', '229236', '248733', '31418', '386525',
       'C.A. 37671', '315088', '7267', '113510', '2695', '2647', '345783',
       '237671', '330931', '330980', 'SC/PARIS 2167', '2691',
       'SOTON/O.Q. 3101310', 'C 7076', '110813', '2626', '14313',
       'PC 17477', '11765', '3101267', '323951', 'C 7077', '113503',
       '2648', '347069', 'PC 17757', '2653', 'STON/O 2. 3101293',
       '349227', '27849', '367655', 'SC 1748', '113760', '350034',
       '3101277', '350052', '350407', '28403', '244278', '240929',
       'STON/O 2. 3101289', '341826', '4137', '315096', '28664', '347064',
       '29106', '312992', '349222', '394140', 'STON/O 2. 3101269',
       '343095', '28220', '250652', '28228', '345773', '349254',
       'A/5. 13032', '315082', '347080', 'A/4. 34244', '2003', '250655',
       '364851', 'SOTON/O.Q. 392078', '110564', '376564', 'SC/AH 3085',
       'STON/O 2. 3101274', '13507', 'C.A. 18723', '345769', '347076',
       '230434', '65306', '33638', '113794', '2666', '113786', '65303',
       '113051', '17453', 'A/5 2817', '349240', '13509', '17464',
       'F.C.C. 13531', '371060', '19952', '364506', '111320', '234360',
       'A/S 2816', 'SOTON/O.Q. 3101306', '113792', '36209', '323592',
       '315089', 'SC/AH Basle 541', '7553', '31027', '3460', '350060',
       '3101298', '239854', 'A/5 3594', '4134', '11771', 'A.5. 18509',
       '65304', 'SOTON/OQ 3101317', '113787', 'PC 17609', 'A/4 45380',
       '36947', 'C.A. 6212', '350035', '315086', '364846', '330909',
       '4135', '26360', '111427', 'C 4001', '382651', 'SOTON/OQ 3101316',
       'PC 17473', 'PC 17603', '349209', '36967', 'C.A. 34260', '226875',
       '349242', '12749', '349252', '2624', '2700', '367232',
       'W./C. 14258', 'PC 17483', '3101296', '29104', '2641', '2690',
       '315084', '113050', 'PC 17761', '364498', '13568', 'WE/P 5735',
       '2908', '693', 'SC/PARIS 2146', '244358', '330979', '2620',
       '347085', '113807', '11755', '345572', '372622', '349251',
       '218629', 'SOTON/OQ 392082', 'SOTON/O.Q. 392087', 'A/4 48871',
       '349205', '2686', '350417', 'S.W./PP 752', '11769', 'PC 17474',
       '14312', 'A/4. 20589', '358585', '243880', '2689',
       'STON/O 2. 3101286', '237789', '13049', '3411', '237565', '13567',
       '14973', 'A./5. 3235', 'STON/O 2. 3101273', 'A/5 3902', '364848',
       'SC/AH 29037', '248727', '2664', '349214', '113796', '364511',
       '111426', '349910', '349246', '113804', 'SOTON/O.Q. 3101305',
       '370377', '364512', '220845', '31028', '2659', '11753', '350029',
       '54636', '36963', '219533', '349224', '334912', '27042', '347743',
       '13214', '112052', '237668', 'STON/O 2. 3101292', '350050',
       '349231', '13213', 'S.O./P.P. 751', 'CA. 2314', '349221', '8475',
       '330919', '365226', '349223', '29751', '2623', '5727', '349210',
       'STON/O 2. 3101285', '234686', '312993', 'A/5 3536', '19996',
       '29750', 'F.C. 12750', 'C.A. 24580', '244270', '239856', '349912',
       '342826', '4138', '330935', '6563', '349228', '350036', '24160',
       '17474', '349256', '2672', '113800', '248731', '363592', '35852',
       '348121', 'PC 17475', '36864', '350025', '223596', 'PC 17476',
       'PC 17482', '113028', '7545', '250647', '348124', '34218', '36568',
       '347062', '350048', '12233', '250643', '113806', '315094', '36866',
       '236853', 'STON/O2. 3101271', '239855', '28425', '233639',
       '349201', '349218', '16988', '376566', 'STON/O 2. 3101288',
       '250648', '113773', '335097', '29103', '392096', '345780',
       '349204', '350042', '29108', '363294', 'SOTON/O2 3101272', '2663',
       '347074', '112379', '364850', '8471', '345781', '350047',
       'S.O./P.P. 3', '2674', '29105', '347078', '383121', '36865',
       '2687', '113501', 'W./C. 6607', 'SOTON/O.Q. 3101312', '374887',
       '3101265', '12460', 'PC 17600', '349203', '28213', '17465',
       '349244', '2685', '2625', '347089', '347063', '112050', '347087',
       '248723', '3474', '28206', '364499', '112058', 'STON/O2. 3101290',
       'S.C./PARIS 2079', 'C 7075', '315098', '19972', '368323', '367228',
       '2671', '347468', '2223', 'PC 17756', '315097', '392092', '11774',
       'SOTON/O2 3101287', '2683', '315090', 'C.A. 5547', '349213',
       '347060', 'PC 17592', '392091', '113055', '2629', '350026',
       '28134', '17466', '233866', '236852', 'SC/PARIS 2149', 'PC 17590',
       '345777', '349248', '695', '345765', '2667', '349212', '349217',
       '349257', '7552', 'C.A./SOTON 34068', 'SOTON/OQ 392076', '211536',
       '112053', '111369', '370376'], dtype=object)

In [ ]:
#Columna 'Cabin'
cabin = data['Cabin'].unique()
print('Cantidad de valores diferentes en la columna "Cabin": ', len(cabin))
print()
cabin

Cantidad de valores diferentes en la columna "Cabin":  148

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [ ]:
#Columna 'Embarked'
embarked = data['Embarked'].unique()
print('Cantidad de valores diferentes en la columna "Embarked": ', len(embarked))
print()
embarked

Cantidad de valores diferentes en la columna "Embarked":  4

array(['S', 'C', 'Q', nan], dtype=object)

## Análisis de Datos

**¿Cuánto es el total que se pagó sumando la tarifa de todos los pasajeros?**

El total que se pagó entre todos los pasajeros fue de 28694 (28693.9493)

In [ ]:
data['Fare'].sum()

28693.9493

**Subconjunto de los datos de los que sobrevivieron**

In [ ]:
data[data['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

**Subconjunto de los datos de los que no sobrevivieron**

In [ ]:
data[data['Survived'] == 0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**Datos de 5 personas que sobrevivieron**

In [ ]:
data1 = data[data['Survived'] == 1]
data1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**Datos de 5 personas que no sobrevivieron**

In [ ]:
data0 = data[data['Survived'] == 0]
data0.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q